### ISSUE TITLE
Check Waveform Fitter scaling

### ISSUE THREAD

**Issue by slowe** [chrisnorth/mma-resources#8] opened 2022-10-26 11:10 UTC
@chrisnorth I've attempted to simplify the code used for the simulation scaling in the Waveform Fitter. So, please would you review the `Scaler()` function on lines 289-320 of [wavefit.js](https://github.com/chrisnorth/mma-resources/blob/main/src/gw/waveform-fitter/resources/wavefit.js) and check if the scaling is being applied properly? It was my attempt to extract the maths from the complicated class that existed before, so it is quite likely that I've got it wrong.

`Scaler(data, mass, dist, inc)` gets passed the waveform as a 2D array along with the mass (M☉), distance (Mpc), and inclination angle (degrees) from the sliders. `Scalar` passes back the modified version of data. `Scalar` is set up with an `M0` (default 65), `D0` (default 420), and `t0` (default 0.423) on line 50.

**Comment by chrisnorth** [comment] 2023-11-06 22:10
Scaling fixed by 8d464fc - need to double check absolute values

**Comment by chrisnorth** [comment] 2023-12-05 20:01
Confirmed that this is working as intended in both "basic" and "advanced"

**Closed as completed by chrisnorth** 2023-12-05 20:01 UTC
Labels: GW
